package com.hzaihua.jfoenix.dao;

import com.hzaihua.jfoenix.entity.InfoNoiseManager;
import java.util.List;

public interface InfoNoiseManagerDao {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table info_noise_manager
     *
     * @mbg.generated
     */
    void insertNoiseManager(InfoNoiseManager infoNoiseManager);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table info_noise_manager
     *
     * @mbg.generated
     */
    void queryNoiseManagerByNoiseCode(String noiseMeasureID);


    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table info_noise_manager
     *
     * @mbg.generated
     */
    void updateNoiseManager(InfoNoiseManager infoNoiseManager);
}