package entity;

import java.io.Serializable;
import java.util.Date;

public class AwaNoiseInstruct implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AWA_noise_instruct.noiseInstructId
     *
     * @mbg.generated
     */
    private String noiseinstructid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AWA_noise_instruct.noiseCode
     *
     * @mbg.generated
     */
    private String noisecode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AWA_noise_instruct.sample
     *
     * @mbg.generated
     */
    private Double sample;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AWA_noise_instruct.upSpace
     *
     * @mbg.generated
     */
    private Integer upspace;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AWA_noise_instruct.timeWight
     *
     * @mbg.generated
     */
    private String timewight;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AWA_noise_instruct.freWight
     *
     * @mbg.generated
     */
    private String frewight;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AWA_noise_instruct.initime
     *
     * @mbg.generated
     */
    private Double initime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AWA_noise_instruct.ON_OFF_MIN
     *
     * @mbg.generated
     */
    private Integer onOffMin;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AWA_noise_instruct.ON_OFF_HOUR
     *
     * @mbg.generated
     */
    private Integer onOffHour;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AWA_noise_instruct.ON_OFF_DAY
     *
     * @mbg.generated
     */
    private Integer onOffDay;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AWA_noise_instruct.isExceed
     *
     * @mbg.generated
     */
    private Integer isexceed;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AWA_noise_instruct.dayOverValue
     *
     * @mbg.generated
     */
    private Double dayovervalue;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AWA_noise_instruct.nightOverValue
     *
     * @mbg.generated
     */
    private Double nightovervalue;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AWA_noise_instruct.overDlay
     *
     * @mbg.generated
     */
    private Double overdlay;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AWA_noise_instruct.isOct
     *
     * @mbg.generated
     */
    private Integer isoct;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AWA_noise_instruct.dayOctValue
     *
     * @mbg.generated
     */
    private Double dayoctvalue;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AWA_noise_instruct.nightOctValue
     *
     * @mbg.generated
     */
    private Double nightoctvalue;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AWA_noise_instruct.octDlay
     *
     * @mbg.generated
     */
    private Double octdlay;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AWA_noise_instruct.ON_OFF_11OCT
     *
     * @mbg.generated
     */
    private Integer onOff11oct;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AWA_noise_instruct.ON_OFF_13OCT
     *
     * @mbg.generated
     */
    private Integer onOff13oct;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AWA_noise_instruct.isRecord
     *
     * @mbg.generated
     */
    private Integer isrecord;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AWA_noise_instruct.dayRecordValue
     *
     * @mbg.generated
     */
    private Double dayrecordvalue;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AWA_noise_instruct.nightRecordValue
     *
     * @mbg.generated
     */
    private Double nightrecordvalue;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AWA_noise_instruct.recordDlay
     *
     * @mbg.generated
     */
    private Double recorddlay;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AWA_noise_instruct.recordModel
     *
     * @mbg.generated
     */
    private Double recordmodel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AWA_noise_instruct.recordStartTime
     *
     * @mbg.generated
     */
    private Date recordstarttime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AWA_noise_instruct.recordEndTime
     *
     * @mbg.generated
     */
    private Date recordendtime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AWA_noise_instruct.isAutoAdjust
     *
     * @mbg.generated
     */
    private Integer isautoadjust;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AWA_noise_instruct.adjustTime
     *
     * @mbg.generated
     */
    private Date adjusttime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AWA_noise_instruct.adjustSpace
     *
     * @mbg.generated
     */
    private Double adjustspace;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AWA_noise_instruct.weaAutoSave
     *
     * @mbg.generated
     */
    private Integer weaautosave;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AWA_noise_instruct.weaAutoUp
     *
     * @mbg.generated
     */
    private Integer weaautoup;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AWA_noise_instruct.weaUpSpace
     *
     * @mbg.generated
     */
    private Double weaupspace;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AWA_noise_instruct.carAutoSave
     *
     * @mbg.generated
     */
    private Integer carautosave;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AWA_noise_instruct.carAutoUp
     *
     * @mbg.generated
     */
    private Integer carautoup;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AWA_noise_instruct.carUpSpace
     *
     * @mbg.generated
     */
    private Double carupspace;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AWA_noise_instruct.dustAutoSave
     *
     * @mbg.generated
     */
    private Integer dustautosave;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AWA_noise_instruct.dustAutoUp
     *
     * @mbg.generated
     */
    private Integer dustautoup;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AWA_noise_instruct.dustUpSpace
     *
     * @mbg.generated
     */
    private Integer dustupspace;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AWA_noise_instruct.ON_OFF_LEQA
     *
     * @mbg.generated
     */
    private Integer onOffLeqa;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AWA_noise_instruct.ON_OFF_LPFA
     *
     * @mbg.generated
     */
    private Integer onOffLpfa;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AWA_noise_instruct.ON_OFF_LPSA
     *
     * @mbg.generated
     */
    private Integer onOffLpsa;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AWA_noise_instruct.ON_OFF_LPIA
     *
     * @mbg.generated
     */
    private Integer onOffLpia;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AWA_noise_instruct.ON_OFF_LEQC
     *
     * @mbg.generated
     */
    private Integer onOffLeqc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AWA_noise_instruct.ON_OFF_LPFC
     *
     * @mbg.generated
     */
    private Integer onOffLpfc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AWA_noise_instruct.ON_OFF_LPSC
     *
     * @mbg.generated
     */
    private Integer onOffLpsc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AWA_noise_instruct.ON_OFF_LPIC
     *
     * @mbg.generated
     */
    private Integer onOffLpic;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AWA_noise_instruct.ON_OFF_LEQZ
     *
     * @mbg.generated
     */
    private Integer onOffLeqz;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AWA_noise_instruct.ON_OFF_LPFZ
     *
     * @mbg.generated
     */
    private Integer onOffLpfz;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AWA_noise_instruct.ON_OFF_LPSZ
     *
     * @mbg.generated
     */
    private Integer onOffLpsz;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AWA_noise_instruct.ON_OFF_LPIZ
     *
     * @mbg.generated
     */
    private Integer onOffLpiz;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AWA_noise_instruct.event_01
     *
     * @mbg.generated
     */
    private Integer event01;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AWA_noise_instruct.event_02
     *
     * @mbg.generated
     */
    private Integer event02;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AWA_noise_instruct.event_03
     *
     * @mbg.generated
     */
    private Integer event03;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AWA_noise_instruct.event_04
     *
     * @mbg.generated
     */
    private Integer event04;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AWA_noise_instruct.event_05
     *
     * @mbg.generated
     */
    private Integer event05;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AWA_noise_instruct.event_06
     *
     * @mbg.generated
     */
    private Integer event06;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AWA_noise_instruct.event_07
     *
     * @mbg.generated
     */
    private Integer event07;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AWA_noise_instruct.event_08
     *
     * @mbg.generated
     */
    private Integer event08;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AWA_noise_instruct.event_09
     *
     * @mbg.generated
     */
    private Integer event09;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AWA_noise_instruct.event_10
     *
     * @mbg.generated
     */
    private Integer event10;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AWA_noise_instruct.event_11
     *
     * @mbg.generated
     */
    private Integer event11;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AWA_noise_instruct.event_12
     *
     * @mbg.generated
     */
    private Integer event12;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AWA_noise_instruct.event_13
     *
     * @mbg.generated
     */
    private Integer event13;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AWA_noise_instruct.ON_OFF_RADF
     *
     * @mbg.generated
     */
    private Integer onOffRadf;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AWA_noise_instruct.ON_OFF_FAMF
     *
     * @mbg.generated
     */
    private Integer onOffFamf;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AWA_noise_instruct.ON_OFF_PDWIV
     *
     * @mbg.generated
     */
    private Integer onOffPdwiv;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table AWA_noise_instruct
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AWA_noise_instruct.noiseInstructId
     *
     * @return the value of AWA_noise_instruct.noiseInstructId
     *
     * @mbg.generated
     */
    public String getNoiseinstructid() {
        return noiseinstructid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AWA_noise_instruct.noiseInstructId
     *
     * @param noiseinstructid the value for AWA_noise_instruct.noiseInstructId
     *
     * @mbg.generated
     */
    public void setNoiseinstructid(String noiseinstructid) {
        this.noiseinstructid = noiseinstructid == null ? null : noiseinstructid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AWA_noise_instruct.noiseCode
     *
     * @return the value of AWA_noise_instruct.noiseCode
     *
     * @mbg.generated
     */
    public String getNoisecode() {
        return noisecode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AWA_noise_instruct.noiseCode
     *
     * @param noisecode the value for AWA_noise_instruct.noiseCode
     *
     * @mbg.generated
     */
    public void setNoisecode(String noisecode) {
        this.noisecode = noisecode == null ? null : noisecode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AWA_noise_instruct.sample
     *
     * @return the value of AWA_noise_instruct.sample
     *
     * @mbg.generated
     */
    public Double getSample() {
        return sample;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AWA_noise_instruct.sample
     *
     * @param sample the value for AWA_noise_instruct.sample
     *
     * @mbg.generated
     */
    public void setSample(Double sample) {
        this.sample = sample;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AWA_noise_instruct.upSpace
     *
     * @return the value of AWA_noise_instruct.upSpace
     *
     * @mbg.generated
     */
    public Integer getUpspace() {
        return upspace;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AWA_noise_instruct.upSpace
     *
     * @param upspace the value for AWA_noise_instruct.upSpace
     *
     * @mbg.generated
     */
    public void setUpspace(Integer upspace) {
        this.upspace = upspace;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AWA_noise_instruct.timeWight
     *
     * @return the value of AWA_noise_instruct.timeWight
     *
     * @mbg.generated
     */
    public String getTimewight() {
        return timewight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AWA_noise_instruct.timeWight
     *
     * @param timewight the value for AWA_noise_instruct.timeWight
     *
     * @mbg.generated
     */
    public void setTimewight(String timewight) {
        this.timewight = timewight == null ? null : timewight.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AWA_noise_instruct.freWight
     *
     * @return the value of AWA_noise_instruct.freWight
     *
     * @mbg.generated
     */
    public String getFrewight() {
        return frewight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AWA_noise_instruct.freWight
     *
     * @param frewight the value for AWA_noise_instruct.freWight
     *
     * @mbg.generated
     */
    public void setFrewight(String frewight) {
        this.frewight = frewight == null ? null : frewight.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AWA_noise_instruct.initime
     *
     * @return the value of AWA_noise_instruct.initime
     *
     * @mbg.generated
     */
    public Double getInitime() {
        return initime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AWA_noise_instruct.initime
     *
     * @param initime the value for AWA_noise_instruct.initime
     *
     * @mbg.generated
     */
    public void setInitime(Double initime) {
        this.initime = initime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AWA_noise_instruct.ON_OFF_MIN
     *
     * @return the value of AWA_noise_instruct.ON_OFF_MIN
     *
     * @mbg.generated
     */
    public Integer getOnOffMin() {
        return onOffMin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AWA_noise_instruct.ON_OFF_MIN
     *
     * @param onOffMin the value for AWA_noise_instruct.ON_OFF_MIN
     *
     * @mbg.generated
     */
    public void setOnOffMin(Integer onOffMin) {
        this.onOffMin = onOffMin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AWA_noise_instruct.ON_OFF_HOUR
     *
     * @return the value of AWA_noise_instruct.ON_OFF_HOUR
     *
     * @mbg.generated
     */
    public Integer getOnOffHour() {
        return onOffHour;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AWA_noise_instruct.ON_OFF_HOUR
     *
     * @param onOffHour the value for AWA_noise_instruct.ON_OFF_HOUR
     *
     * @mbg.generated
     */
    public void setOnOffHour(Integer onOffHour) {
        this.onOffHour = onOffHour;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AWA_noise_instruct.ON_OFF_DAY
     *
     * @return the value of AWA_noise_instruct.ON_OFF_DAY
     *
     * @mbg.generated
     */
    public Integer getOnOffDay() {
        return onOffDay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AWA_noise_instruct.ON_OFF_DAY
     *
     * @param onOffDay the value for AWA_noise_instruct.ON_OFF_DAY
     *
     * @mbg.generated
     */
    public void setOnOffDay(Integer onOffDay) {
        this.onOffDay = onOffDay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AWA_noise_instruct.isExceed
     *
     * @return the value of AWA_noise_instruct.isExceed
     *
     * @mbg.generated
     */
    public Integer getIsexceed() {
        return isexceed;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AWA_noise_instruct.isExceed
     *
     * @param isexceed the value for AWA_noise_instruct.isExceed
     *
     * @mbg.generated
     */
    public void setIsexceed(Integer isexceed) {
        this.isexceed = isexceed;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AWA_noise_instruct.dayOverValue
     *
     * @return the value of AWA_noise_instruct.dayOverValue
     *
     * @mbg.generated
     */
    public Double getDayovervalue() {
        return dayovervalue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AWA_noise_instruct.dayOverValue
     *
     * @param dayovervalue the value for AWA_noise_instruct.dayOverValue
     *
     * @mbg.generated
     */
    public void setDayovervalue(Double dayovervalue) {
        this.dayovervalue = dayovervalue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AWA_noise_instruct.nightOverValue
     *
     * @return the value of AWA_noise_instruct.nightOverValue
     *
     * @mbg.generated
     */
    public Double getNightovervalue() {
        return nightovervalue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AWA_noise_instruct.nightOverValue
     *
     * @param nightovervalue the value for AWA_noise_instruct.nightOverValue
     *
     * @mbg.generated
     */
    public void setNightovervalue(Double nightovervalue) {
        this.nightovervalue = nightovervalue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AWA_noise_instruct.overDlay
     *
     * @return the value of AWA_noise_instruct.overDlay
     *
     * @mbg.generated
     */
    public Double getOverdlay() {
        return overdlay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AWA_noise_instruct.overDlay
     *
     * @param overdlay the value for AWA_noise_instruct.overDlay
     *
     * @mbg.generated
     */
    public void setOverdlay(Double overdlay) {
        this.overdlay = overdlay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AWA_noise_instruct.isOct
     *
     * @return the value of AWA_noise_instruct.isOct
     *
     * @mbg.generated
     */
    public Integer getIsoct() {
        return isoct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AWA_noise_instruct.isOct
     *
     * @param isoct the value for AWA_noise_instruct.isOct
     *
     * @mbg.generated
     */
    public void setIsoct(Integer isoct) {
        this.isoct = isoct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AWA_noise_instruct.dayOctValue
     *
     * @return the value of AWA_noise_instruct.dayOctValue
     *
     * @mbg.generated
     */
    public Double getDayoctvalue() {
        return dayoctvalue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AWA_noise_instruct.dayOctValue
     *
     * @param dayoctvalue the value for AWA_noise_instruct.dayOctValue
     *
     * @mbg.generated
     */
    public void setDayoctvalue(Double dayoctvalue) {
        this.dayoctvalue = dayoctvalue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AWA_noise_instruct.nightOctValue
     *
     * @return the value of AWA_noise_instruct.nightOctValue
     *
     * @mbg.generated
     */
    public Double getNightoctvalue() {
        return nightoctvalue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AWA_noise_instruct.nightOctValue
     *
     * @param nightoctvalue the value for AWA_noise_instruct.nightOctValue
     *
     * @mbg.generated
     */
    public void setNightoctvalue(Double nightoctvalue) {
        this.nightoctvalue = nightoctvalue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AWA_noise_instruct.octDlay
     *
     * @return the value of AWA_noise_instruct.octDlay
     *
     * @mbg.generated
     */
    public Double getOctdlay() {
        return octdlay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AWA_noise_instruct.octDlay
     *
     * @param octdlay the value for AWA_noise_instruct.octDlay
     *
     * @mbg.generated
     */
    public void setOctdlay(Double octdlay) {
        this.octdlay = octdlay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AWA_noise_instruct.ON_OFF_11OCT
     *
     * @return the value of AWA_noise_instruct.ON_OFF_11OCT
     *
     * @mbg.generated
     */
    public Integer getOnOff11oct() {
        return onOff11oct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AWA_noise_instruct.ON_OFF_11OCT
     *
     * @param onOff11oct the value for AWA_noise_instruct.ON_OFF_11OCT
     *
     * @mbg.generated
     */
    public void setOnOff11oct(Integer onOff11oct) {
        this.onOff11oct = onOff11oct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AWA_noise_instruct.ON_OFF_13OCT
     *
     * @return the value of AWA_noise_instruct.ON_OFF_13OCT
     *
     * @mbg.generated
     */
    public Integer getOnOff13oct() {
        return onOff13oct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AWA_noise_instruct.ON_OFF_13OCT
     *
     * @param onOff13oct the value for AWA_noise_instruct.ON_OFF_13OCT
     *
     * @mbg.generated
     */
    public void setOnOff13oct(Integer onOff13oct) {
        this.onOff13oct = onOff13oct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AWA_noise_instruct.isRecord
     *
     * @return the value of AWA_noise_instruct.isRecord
     *
     * @mbg.generated
     */
    public Integer getIsrecord() {
        return isrecord;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AWA_noise_instruct.isRecord
     *
     * @param isrecord the value for AWA_noise_instruct.isRecord
     *
     * @mbg.generated
     */
    public void setIsrecord(Integer isrecord) {
        this.isrecord = isrecord;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AWA_noise_instruct.dayRecordValue
     *
     * @return the value of AWA_noise_instruct.dayRecordValue
     *
     * @mbg.generated
     */
    public Double getDayrecordvalue() {
        return dayrecordvalue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AWA_noise_instruct.dayRecordValue
     *
     * @param dayrecordvalue the value for AWA_noise_instruct.dayRecordValue
     *
     * @mbg.generated
     */
    public void setDayrecordvalue(Double dayrecordvalue) {
        this.dayrecordvalue = dayrecordvalue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AWA_noise_instruct.nightRecordValue
     *
     * @return the value of AWA_noise_instruct.nightRecordValue
     *
     * @mbg.generated
     */
    public Double getNightrecordvalue() {
        return nightrecordvalue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AWA_noise_instruct.nightRecordValue
     *
     * @param nightrecordvalue the value for AWA_noise_instruct.nightRecordValue
     *
     * @mbg.generated
     */
    public void setNightrecordvalue(Double nightrecordvalue) {
        this.nightrecordvalue = nightrecordvalue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AWA_noise_instruct.recordDlay
     *
     * @return the value of AWA_noise_instruct.recordDlay
     *
     * @mbg.generated
     */
    public Double getRecorddlay() {
        return recorddlay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AWA_noise_instruct.recordDlay
     *
     * @param recorddlay the value for AWA_noise_instruct.recordDlay
     *
     * @mbg.generated
     */
    public void setRecorddlay(Double recorddlay) {
        this.recorddlay = recorddlay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AWA_noise_instruct.recordModel
     *
     * @return the value of AWA_noise_instruct.recordModel
     *
     * @mbg.generated
     */
    public Double getRecordmodel() {
        return recordmodel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AWA_noise_instruct.recordModel
     *
     * @param recordmodel the value for AWA_noise_instruct.recordModel
     *
     * @mbg.generated
     */
    public void setRecordmodel(Double recordmodel) {
        this.recordmodel = recordmodel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AWA_noise_instruct.recordStartTime
     *
     * @return the value of AWA_noise_instruct.recordStartTime
     *
     * @mbg.generated
     */
    public Date getRecordstarttime() {
        return recordstarttime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AWA_noise_instruct.recordStartTime
     *
     * @param recordstarttime the value for AWA_noise_instruct.recordStartTime
     *
     * @mbg.generated
     */
    public void setRecordstarttime(Date recordstarttime) {
        this.recordstarttime = recordstarttime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AWA_noise_instruct.recordEndTime
     *
     * @return the value of AWA_noise_instruct.recordEndTime
     *
     * @mbg.generated
     */
    public Date getRecordendtime() {
        return recordendtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AWA_noise_instruct.recordEndTime
     *
     * @param recordendtime the value for AWA_noise_instruct.recordEndTime
     *
     * @mbg.generated
     */
    public void setRecordendtime(Date recordendtime) {
        this.recordendtime = recordendtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AWA_noise_instruct.isAutoAdjust
     *
     * @return the value of AWA_noise_instruct.isAutoAdjust
     *
     * @mbg.generated
     */
    public Integer getIsautoadjust() {
        return isautoadjust;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AWA_noise_instruct.isAutoAdjust
     *
     * @param isautoadjust the value for AWA_noise_instruct.isAutoAdjust
     *
     * @mbg.generated
     */
    public void setIsautoadjust(Integer isautoadjust) {
        this.isautoadjust = isautoadjust;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AWA_noise_instruct.adjustTime
     *
     * @return the value of AWA_noise_instruct.adjustTime
     *
     * @mbg.generated
     */
    public Date getAdjusttime() {
        return adjusttime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AWA_noise_instruct.adjustTime
     *
     * @param adjusttime the value for AWA_noise_instruct.adjustTime
     *
     * @mbg.generated
     */
    public void setAdjusttime(Date adjusttime) {
        this.adjusttime = adjusttime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AWA_noise_instruct.adjustSpace
     *
     * @return the value of AWA_noise_instruct.adjustSpace
     *
     * @mbg.generated
     */
    public Double getAdjustspace() {
        return adjustspace;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AWA_noise_instruct.adjustSpace
     *
     * @param adjustspace the value for AWA_noise_instruct.adjustSpace
     *
     * @mbg.generated
     */
    public void setAdjustspace(Double adjustspace) {
        this.adjustspace = adjustspace;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AWA_noise_instruct.weaAutoSave
     *
     * @return the value of AWA_noise_instruct.weaAutoSave
     *
     * @mbg.generated
     */
    public Integer getWeaautosave() {
        return weaautosave;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AWA_noise_instruct.weaAutoSave
     *
     * @param weaautosave the value for AWA_noise_instruct.weaAutoSave
     *
     * @mbg.generated
     */
    public void setWeaautosave(Integer weaautosave) {
        this.weaautosave = weaautosave;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AWA_noise_instruct.weaAutoUp
     *
     * @return the value of AWA_noise_instruct.weaAutoUp
     *
     * @mbg.generated
     */
    public Integer getWeaautoup() {
        return weaautoup;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AWA_noise_instruct.weaAutoUp
     *
     * @param weaautoup the value for AWA_noise_instruct.weaAutoUp
     *
     * @mbg.generated
     */
    public void setWeaautoup(Integer weaautoup) {
        this.weaautoup = weaautoup;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AWA_noise_instruct.weaUpSpace
     *
     * @return the value of AWA_noise_instruct.weaUpSpace
     *
     * @mbg.generated
     */
    public Double getWeaupspace() {
        return weaupspace;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AWA_noise_instruct.weaUpSpace
     *
     * @param weaupspace the value for AWA_noise_instruct.weaUpSpace
     *
     * @mbg.generated
     */
    public void setWeaupspace(Double weaupspace) {
        this.weaupspace = weaupspace;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AWA_noise_instruct.carAutoSave
     *
     * @return the value of AWA_noise_instruct.carAutoSave
     *
     * @mbg.generated
     */
    public Integer getCarautosave() {
        return carautosave;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AWA_noise_instruct.carAutoSave
     *
     * @param carautosave the value for AWA_noise_instruct.carAutoSave
     *
     * @mbg.generated
     */
    public void setCarautosave(Integer carautosave) {
        this.carautosave = carautosave;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AWA_noise_instruct.carAutoUp
     *
     * @return the value of AWA_noise_instruct.carAutoUp
     *
     * @mbg.generated
     */
    public Integer getCarautoup() {
        return carautoup;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AWA_noise_instruct.carAutoUp
     *
     * @param carautoup the value for AWA_noise_instruct.carAutoUp
     *
     * @mbg.generated
     */
    public void setCarautoup(Integer carautoup) {
        this.carautoup = carautoup;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AWA_noise_instruct.carUpSpace
     *
     * @return the value of AWA_noise_instruct.carUpSpace
     *
     * @mbg.generated
     */
    public Double getCarupspace() {
        return carupspace;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AWA_noise_instruct.carUpSpace
     *
     * @param carupspace the value for AWA_noise_instruct.carUpSpace
     *
     * @mbg.generated
     */
    public void setCarupspace(Double carupspace) {
        this.carupspace = carupspace;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AWA_noise_instruct.dustAutoSave
     *
     * @return the value of AWA_noise_instruct.dustAutoSave
     *
     * @mbg.generated
     */
    public Integer getDustautosave() {
        return dustautosave;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AWA_noise_instruct.dustAutoSave
     *
     * @param dustautosave the value for AWA_noise_instruct.dustAutoSave
     *
     * @mbg.generated
     */
    public void setDustautosave(Integer dustautosave) {
        this.dustautosave = dustautosave;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AWA_noise_instruct.dustAutoUp
     *
     * @return the value of AWA_noise_instruct.dustAutoUp
     *
     * @mbg.generated
     */
    public Integer getDustautoup() {
        return dustautoup;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AWA_noise_instruct.dustAutoUp
     *
     * @param dustautoup the value for AWA_noise_instruct.dustAutoUp
     *
     * @mbg.generated
     */
    public void setDustautoup(Integer dustautoup) {
        this.dustautoup = dustautoup;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AWA_noise_instruct.dustUpSpace
     *
     * @return the value of AWA_noise_instruct.dustUpSpace
     *
     * @mbg.generated
     */
    public Integer getDustupspace() {
        return dustupspace;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AWA_noise_instruct.dustUpSpace
     *
     * @param dustupspace the value for AWA_noise_instruct.dustUpSpace
     *
     * @mbg.generated
     */
    public void setDustupspace(Integer dustupspace) {
        this.dustupspace = dustupspace;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AWA_noise_instruct.ON_OFF_LEQA
     *
     * @return the value of AWA_noise_instruct.ON_OFF_LEQA
     *
     * @mbg.generated
     */
    public Integer getOnOffLeqa() {
        return onOffLeqa;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AWA_noise_instruct.ON_OFF_LEQA
     *
     * @param onOffLeqa the value for AWA_noise_instruct.ON_OFF_LEQA
     *
     * @mbg.generated
     */
    public void setOnOffLeqa(Integer onOffLeqa) {
        this.onOffLeqa = onOffLeqa;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AWA_noise_instruct.ON_OFF_LPFA
     *
     * @return the value of AWA_noise_instruct.ON_OFF_LPFA
     *
     * @mbg.generated
     */
    public Integer getOnOffLpfa() {
        return onOffLpfa;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AWA_noise_instruct.ON_OFF_LPFA
     *
     * @param onOffLpfa the value for AWA_noise_instruct.ON_OFF_LPFA
     *
     * @mbg.generated
     */
    public void setOnOffLpfa(Integer onOffLpfa) {
        this.onOffLpfa = onOffLpfa;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AWA_noise_instruct.ON_OFF_LPSA
     *
     * @return the value of AWA_noise_instruct.ON_OFF_LPSA
     *
     * @mbg.generated
     */
    public Integer getOnOffLpsa() {
        return onOffLpsa;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AWA_noise_instruct.ON_OFF_LPSA
     *
     * @param onOffLpsa the value for AWA_noise_instruct.ON_OFF_LPSA
     *
     * @mbg.generated
     */
    public void setOnOffLpsa(Integer onOffLpsa) {
        this.onOffLpsa = onOffLpsa;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AWA_noise_instruct.ON_OFF_LPIA
     *
     * @return the value of AWA_noise_instruct.ON_OFF_LPIA
     *
     * @mbg.generated
     */
    public Integer getOnOffLpia() {
        return onOffLpia;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AWA_noise_instruct.ON_OFF_LPIA
     *
     * @param onOffLpia the value for AWA_noise_instruct.ON_OFF_LPIA
     *
     * @mbg.generated
     */
    public void setOnOffLpia(Integer onOffLpia) {
        this.onOffLpia = onOffLpia;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AWA_noise_instruct.ON_OFF_LEQC
     *
     * @return the value of AWA_noise_instruct.ON_OFF_LEQC
     *
     * @mbg.generated
     */
    public Integer getOnOffLeqc() {
        return onOffLeqc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AWA_noise_instruct.ON_OFF_LEQC
     *
     * @param onOffLeqc the value for AWA_noise_instruct.ON_OFF_LEQC
     *
     * @mbg.generated
     */
    public void setOnOffLeqc(Integer onOffLeqc) {
        this.onOffLeqc = onOffLeqc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AWA_noise_instruct.ON_OFF_LPFC
     *
     * @return the value of AWA_noise_instruct.ON_OFF_LPFC
     *
     * @mbg.generated
     */
    public Integer getOnOffLpfc() {
        return onOffLpfc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AWA_noise_instruct.ON_OFF_LPFC
     *
     * @param onOffLpfc the value for AWA_noise_instruct.ON_OFF_LPFC
     *
     * @mbg.generated
     */
    public void setOnOffLpfc(Integer onOffLpfc) {
        this.onOffLpfc = onOffLpfc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AWA_noise_instruct.ON_OFF_LPSC
     *
     * @return the value of AWA_noise_instruct.ON_OFF_LPSC
     *
     * @mbg.generated
     */
    public Integer getOnOffLpsc() {
        return onOffLpsc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AWA_noise_instruct.ON_OFF_LPSC
     *
     * @param onOffLpsc the value for AWA_noise_instruct.ON_OFF_LPSC
     *
     * @mbg.generated
     */
    public void setOnOffLpsc(Integer onOffLpsc) {
        this.onOffLpsc = onOffLpsc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AWA_noise_instruct.ON_OFF_LPIC
     *
     * @return the value of AWA_noise_instruct.ON_OFF_LPIC
     *
     * @mbg.generated
     */
    public Integer getOnOffLpic() {
        return onOffLpic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AWA_noise_instruct.ON_OFF_LPIC
     *
     * @param onOffLpic the value for AWA_noise_instruct.ON_OFF_LPIC
     *
     * @mbg.generated
     */
    public void setOnOffLpic(Integer onOffLpic) {
        this.onOffLpic = onOffLpic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AWA_noise_instruct.ON_OFF_LEQZ
     *
     * @return the value of AWA_noise_instruct.ON_OFF_LEQZ
     *
     * @mbg.generated
     */
    public Integer getOnOffLeqz() {
        return onOffLeqz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AWA_noise_instruct.ON_OFF_LEQZ
     *
     * @param onOffLeqz the value for AWA_noise_instruct.ON_OFF_LEQZ
     *
     * @mbg.generated
     */
    public void setOnOffLeqz(Integer onOffLeqz) {
        this.onOffLeqz = onOffLeqz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AWA_noise_instruct.ON_OFF_LPFZ
     *
     * @return the value of AWA_noise_instruct.ON_OFF_LPFZ
     *
     * @mbg.generated
     */
    public Integer getOnOffLpfz() {
        return onOffLpfz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AWA_noise_instruct.ON_OFF_LPFZ
     *
     * @param onOffLpfz the value for AWA_noise_instruct.ON_OFF_LPFZ
     *
     * @mbg.generated
     */
    public void setOnOffLpfz(Integer onOffLpfz) {
        this.onOffLpfz = onOffLpfz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AWA_noise_instruct.ON_OFF_LPSZ
     *
     * @return the value of AWA_noise_instruct.ON_OFF_LPSZ
     *
     * @mbg.generated
     */
    public Integer getOnOffLpsz() {
        return onOffLpsz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AWA_noise_instruct.ON_OFF_LPSZ
     *
     * @param onOffLpsz the value for AWA_noise_instruct.ON_OFF_LPSZ
     *
     * @mbg.generated
     */
    public void setOnOffLpsz(Integer onOffLpsz) {
        this.onOffLpsz = onOffLpsz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AWA_noise_instruct.ON_OFF_LPIZ
     *
     * @return the value of AWA_noise_instruct.ON_OFF_LPIZ
     *
     * @mbg.generated
     */
    public Integer getOnOffLpiz() {
        return onOffLpiz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AWA_noise_instruct.ON_OFF_LPIZ
     *
     * @param onOffLpiz the value for AWA_noise_instruct.ON_OFF_LPIZ
     *
     * @mbg.generated
     */
    public void setOnOffLpiz(Integer onOffLpiz) {
        this.onOffLpiz = onOffLpiz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AWA_noise_instruct.event_01
     *
     * @return the value of AWA_noise_instruct.event_01
     *
     * @mbg.generated
     */
    public Integer getEvent01() {
        return event01;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AWA_noise_instruct.event_01
     *
     * @param event01 the value for AWA_noise_instruct.event_01
     *
     * @mbg.generated
     */
    public void setEvent01(Integer event01) {
        this.event01 = event01;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AWA_noise_instruct.event_02
     *
     * @return the value of AWA_noise_instruct.event_02
     *
     * @mbg.generated
     */
    public Integer getEvent02() {
        return event02;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AWA_noise_instruct.event_02
     *
     * @param event02 the value for AWA_noise_instruct.event_02
     *
     * @mbg.generated
     */
    public void setEvent02(Integer event02) {
        this.event02 = event02;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AWA_noise_instruct.event_03
     *
     * @return the value of AWA_noise_instruct.event_03
     *
     * @mbg.generated
     */
    public Integer getEvent03() {
        return event03;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AWA_noise_instruct.event_03
     *
     * @param event03 the value for AWA_noise_instruct.event_03
     *
     * @mbg.generated
     */
    public void setEvent03(Integer event03) {
        this.event03 = event03;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AWA_noise_instruct.event_04
     *
     * @return the value of AWA_noise_instruct.event_04
     *
     * @mbg.generated
     */
    public Integer getEvent04() {
        return event04;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AWA_noise_instruct.event_04
     *
     * @param event04 the value for AWA_noise_instruct.event_04
     *
     * @mbg.generated
     */
    public void setEvent04(Integer event04) {
        this.event04 = event04;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AWA_noise_instruct.event_05
     *
     * @return the value of AWA_noise_instruct.event_05
     *
     * @mbg.generated
     */
    public Integer getEvent05() {
        return event05;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AWA_noise_instruct.event_05
     *
     * @param event05 the value for AWA_noise_instruct.event_05
     *
     * @mbg.generated
     */
    public void setEvent05(Integer event05) {
        this.event05 = event05;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AWA_noise_instruct.event_06
     *
     * @return the value of AWA_noise_instruct.event_06
     *
     * @mbg.generated
     */
    public Integer getEvent06() {
        return event06;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AWA_noise_instruct.event_06
     *
     * @param event06 the value for AWA_noise_instruct.event_06
     *
     * @mbg.generated
     */
    public void setEvent06(Integer event06) {
        this.event06 = event06;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AWA_noise_instruct.event_07
     *
     * @return the value of AWA_noise_instruct.event_07
     *
     * @mbg.generated
     */
    public Integer getEvent07() {
        return event07;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AWA_noise_instruct.event_07
     *
     * @param event07 the value for AWA_noise_instruct.event_07
     *
     * @mbg.generated
     */
    public void setEvent07(Integer event07) {
        this.event07 = event07;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AWA_noise_instruct.event_08
     *
     * @return the value of AWA_noise_instruct.event_08
     *
     * @mbg.generated
     */
    public Integer getEvent08() {
        return event08;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AWA_noise_instruct.event_08
     *
     * @param event08 the value for AWA_noise_instruct.event_08
     *
     * @mbg.generated
     */
    public void setEvent08(Integer event08) {
        this.event08 = event08;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AWA_noise_instruct.event_09
     *
     * @return the value of AWA_noise_instruct.event_09
     *
     * @mbg.generated
     */
    public Integer getEvent09() {
        return event09;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AWA_noise_instruct.event_09
     *
     * @param event09 the value for AWA_noise_instruct.event_09
     *
     * @mbg.generated
     */
    public void setEvent09(Integer event09) {
        this.event09 = event09;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AWA_noise_instruct.event_10
     *
     * @return the value of AWA_noise_instruct.event_10
     *
     * @mbg.generated
     */
    public Integer getEvent10() {
        return event10;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AWA_noise_instruct.event_10
     *
     * @param event10 the value for AWA_noise_instruct.event_10
     *
     * @mbg.generated
     */
    public void setEvent10(Integer event10) {
        this.event10 = event10;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AWA_noise_instruct.event_11
     *
     * @return the value of AWA_noise_instruct.event_11
     *
     * @mbg.generated
     */
    public Integer getEvent11() {
        return event11;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AWA_noise_instruct.event_11
     *
     * @param event11 the value for AWA_noise_instruct.event_11
     *
     * @mbg.generated
     */
    public void setEvent11(Integer event11) {
        this.event11 = event11;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AWA_noise_instruct.event_12
     *
     * @return the value of AWA_noise_instruct.event_12
     *
     * @mbg.generated
     */
    public Integer getEvent12() {
        return event12;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AWA_noise_instruct.event_12
     *
     * @param event12 the value for AWA_noise_instruct.event_12
     *
     * @mbg.generated
     */
    public void setEvent12(Integer event12) {
        this.event12 = event12;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AWA_noise_instruct.event_13
     *
     * @return the value of AWA_noise_instruct.event_13
     *
     * @mbg.generated
     */
    public Integer getEvent13() {
        return event13;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AWA_noise_instruct.event_13
     *
     * @param event13 the value for AWA_noise_instruct.event_13
     *
     * @mbg.generated
     */
    public void setEvent13(Integer event13) {
        this.event13 = event13;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AWA_noise_instruct.ON_OFF_RADF
     *
     * @return the value of AWA_noise_instruct.ON_OFF_RADF
     *
     * @mbg.generated
     */
    public Integer getOnOffRadf() {
        return onOffRadf;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AWA_noise_instruct.ON_OFF_RADF
     *
     * @param onOffRadf the value for AWA_noise_instruct.ON_OFF_RADF
     *
     * @mbg.generated
     */
    public void setOnOffRadf(Integer onOffRadf) {
        this.onOffRadf = onOffRadf;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AWA_noise_instruct.ON_OFF_FAMF
     *
     * @return the value of AWA_noise_instruct.ON_OFF_FAMF
     *
     * @mbg.generated
     */
    public Integer getOnOffFamf() {
        return onOffFamf;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AWA_noise_instruct.ON_OFF_FAMF
     *
     * @param onOffFamf the value for AWA_noise_instruct.ON_OFF_FAMF
     *
     * @mbg.generated
     */
    public void setOnOffFamf(Integer onOffFamf) {
        this.onOffFamf = onOffFamf;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AWA_noise_instruct.ON_OFF_PDWIV
     *
     * @return the value of AWA_noise_instruct.ON_OFF_PDWIV
     *
     * @mbg.generated
     */
    public Integer getOnOffPdwiv() {
        return onOffPdwiv;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AWA_noise_instruct.ON_OFF_PDWIV
     *
     * @param onOffPdwiv the value for AWA_noise_instruct.ON_OFF_PDWIV
     *
     * @mbg.generated
     */
    public void setOnOffPdwiv(Integer onOffPdwiv) {
        this.onOffPdwiv = onOffPdwiv;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AWA_noise_instruct
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", noiseinstructid=").append(noiseinstructid);
        sb.append(", noisecode=").append(noisecode);
        sb.append(", sample=").append(sample);
        sb.append(", upspace=").append(upspace);
        sb.append(", timewight=").append(timewight);
        sb.append(", frewight=").append(frewight);
        sb.append(", initime=").append(initime);
        sb.append(", onOffMin=").append(onOffMin);
        sb.append(", onOffHour=").append(onOffHour);
        sb.append(", onOffDay=").append(onOffDay);
        sb.append(", isexceed=").append(isexceed);
        sb.append(", dayovervalue=").append(dayovervalue);
        sb.append(", nightovervalue=").append(nightovervalue);
        sb.append(", overdlay=").append(overdlay);
        sb.append(", isoct=").append(isoct);
        sb.append(", dayoctvalue=").append(dayoctvalue);
        sb.append(", nightoctvalue=").append(nightoctvalue);
        sb.append(", octdlay=").append(octdlay);
        sb.append(", onOff11oct=").append(onOff11oct);
        sb.append(", onOff13oct=").append(onOff13oct);
        sb.append(", isrecord=").append(isrecord);
        sb.append(", dayrecordvalue=").append(dayrecordvalue);
        sb.append(", nightrecordvalue=").append(nightrecordvalue);
        sb.append(", recorddlay=").append(recorddlay);
        sb.append(", recordmodel=").append(recordmodel);
        sb.append(", recordstarttime=").append(recordstarttime);
        sb.append(", recordendtime=").append(recordendtime);
        sb.append(", isautoadjust=").append(isautoadjust);
        sb.append(", adjusttime=").append(adjusttime);
        sb.append(", adjustspace=").append(adjustspace);
        sb.append(", weaautosave=").append(weaautosave);
        sb.append(", weaautoup=").append(weaautoup);
        sb.append(", weaupspace=").append(weaupspace);
        sb.append(", carautosave=").append(carautosave);
        sb.append(", carautoup=").append(carautoup);
        sb.append(", carupspace=").append(carupspace);
        sb.append(", dustautosave=").append(dustautosave);
        sb.append(", dustautoup=").append(dustautoup);
        sb.append(", dustupspace=").append(dustupspace);
        sb.append(", onOffLeqa=").append(onOffLeqa);
        sb.append(", onOffLpfa=").append(onOffLpfa);
        sb.append(", onOffLpsa=").append(onOffLpsa);
        sb.append(", onOffLpia=").append(onOffLpia);
        sb.append(", onOffLeqc=").append(onOffLeqc);
        sb.append(", onOffLpfc=").append(onOffLpfc);
        sb.append(", onOffLpsc=").append(onOffLpsc);
        sb.append(", onOffLpic=").append(onOffLpic);
        sb.append(", onOffLeqz=").append(onOffLeqz);
        sb.append(", onOffLpfz=").append(onOffLpfz);
        sb.append(", onOffLpsz=").append(onOffLpsz);
        sb.append(", onOffLpiz=").append(onOffLpiz);
        sb.append(", event01=").append(event01);
        sb.append(", event02=").append(event02);
        sb.append(", event03=").append(event03);
        sb.append(", event04=").append(event04);
        sb.append(", event05=").append(event05);
        sb.append(", event06=").append(event06);
        sb.append(", event07=").append(event07);
        sb.append(", event08=").append(event08);
        sb.append(", event09=").append(event09);
        sb.append(", event10=").append(event10);
        sb.append(", event11=").append(event11);
        sb.append(", event12=").append(event12);
        sb.append(", event13=").append(event13);
        sb.append(", onOffRadf=").append(onOffRadf);
        sb.append(", onOffFamf=").append(onOffFamf);
        sb.append(", onOffPdwiv=").append(onOffPdwiv);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}